[package]
name = "atplt-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roaring = "0.10"
itertools = "0.12"
rustc-hash = "1.1"
